apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-operator-example
spec:
  replicas: 1
  selector:
    matchLabels:
      name: k8s-operator-example
  template:
    metadata:
      labels:
        name: k8s-operator-example
    spec:
      containers:
        - name: k8s-operator-example
          image: onuryilmaz/k8s-operator-example
          command:
          - k8s-operator-example
          imagePullPolicy: Always
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: k8s-operator-example
rules:
- apiGroups:
  - k8s.packt.com
  resources:
  - "*"
  verbs:
  - "*"
- apiGroups:
  - ""
  resources:
  - pods
  - services
  - endpoints
  - persistentvolumeclaims
  - events
  - configmaps
  - secrets
  verbs:
  - "*"
- apiGroups:
  - apps
  resources:
  - deployments
  - daemonsets
  - replicasets
  - statefulsets
  verbs:
  - "*"
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: default-account-k8s-operator-example
subjects:
- kind: ServiceAccount
  name: default
roleRef:
  kind: Role
  name: k8s-operator-example
  apiGroup: rbac.authorization.k8s.io